-- DEPRECATED: This legacy script formerly created permissive policies for anonymous users.
-- Its executable SQL has been intentionally removed to make accidental execution harmless.
-- For an Auth-enabled deployment, use supabase_auth_security.sql only after the matching
-- frontend changes have been deployed and the migration has been reviewed for the target project.
