const assert = require('assert');
const fs = require('fs');

const source = fs.readFileSync('src/main.js', 'utf8');
const css = fs.readFileSync('src/style.css', 'utf8');
const indexHtml = fs.readFileSync('index.html', 'utf8');
const migration = fs.readFileSync('supabase_question_templates.sql', 'utf8');

assert(source.includes("const composerModules = module === 'templates' || module === 'questions' || module === 'exams';"), 'Admin must route Template, Question Bank, and Exam tabs into Soạn Đề.');
assert(indexHtml.includes('id="admin-compose-cards"'), 'Admin must expose the Template, Question Bank, and Exam workspaces in Soạn Đề.');
assert(source.includes('renderTemplates(box)'), 'Admin must render the Template Bank.');
assert(source.includes("setTemplateFilter('classlevel'"), 'Template Bank must offer grade filtering.');
assert(source.includes('template-common-question'), 'Template editor must offer an editable common question.');
assert(source.includes('template-content-builder'), 'Template editor must offer visual blocks for each subquestion.');
assert(source.includes('template-editor'), 'Template editor must use the full modal width through its dedicated layout.');
assert(source.includes('template-preview-dialog'), 'Template editor must expose a focused question preview dialog.');
assert(source.includes('template-preview-open'), 'Template editor must expose an explicit Preview action.');
assert(source.includes('1. Đề mới'), 'Preview must offer saving the question into a new exam.');
assert(source.includes('2. Đề có sẵn'), 'Preview must offer saving the question into an existing exam.');
assert(source.includes('Quay trở lại'), 'Preview must offer a return action.');
assert(!source.includes('Giao diện khi học sinh làm bài'), 'Template editor must not embed the old gameplay interface panel.');
assert(!source.includes('Ví dụ kết quả:'), 'Template editor must not use text-only "Ví dụ kết quả" previews.');
assert(source.includes('<b>Diễn giải</b>'), 'Template editor must label the template summary as Diễn giải.');
assert(!source.includes('Ví dụ khai báo'), 'Template editor must no longer present the summary as an example declaration.');
assert(source.includes('Số lượng chữ số ít nhất'), 'Four-arithmetic templates must clearly describe the minimum digit count.');
assert(source.includes('Số lượng chữ số nhiều nhất'), 'Four-arithmetic templates must clearly describe the maximum digit count.');
assert(css.includes('template-editor__arithmetic-settings'), 'Arithmetic settings must use the compact grid layout.');
assert(css.includes('width: 74px'), 'Range inputs must stay compact instead of stretching across the editor.');
assert(source.includes('onclick="app.admin.renderTemplateForm(null)"'), 'Template Bank must offer a blank template creation flow.');
assert(source.includes('btn-template-create'), 'Template Bank must expose a visible create-template action.');
assert(source.includes('template-library-card'), 'Template Bank must render interactive template cards.');
assert(source.includes('Lưu thành bản mới'), 'Template editor must allow copying an existing configuration.');
assert(source.includes('template-select-all'), 'Template editor must provide quick select-all controls.');
assert(source.includes('hundredBillions'), 'Template editor must support place values through hundreds of billions.');
assert(source.includes('formatMathText'), 'Math content must format long numbers with textbook-style spaces.');
assert(source.includes('formatTemplateNumberInput'), 'Template range inputs must format numbers while editing.');
assert(!source.includes('template-variables'), 'Template editor must omit the redundant insertable-variable panel.');
assert(source.includes('template-part-checkbox'), 'Template editor must expose a checkbox for each default subquestion.');
assert(source.includes('template-part-count'), 'Template editor must expose the supported 1/2/4 subquestion counts.');
assert(source.includes('exam-structured-part__checkbox'), 'Exam question editors must expose a checkbox for each structured subquestion.');
assert(source.includes('getEmptyExamQuestionDraft'), 'Blank exam composer cards must start with four editable subquestions.');
assert(source.includes('getValidPartAnswerCounts'), 'Question scoring must validate grouped subquestion answers.');
assert(source.includes('TemplateContentBuilder'), 'Templates stored with {question} must use the visual presentation builder.');
assert(source.includes('defaultPrompt'), 'Every dynamic template must declare its readable default prompt.');
assert(!source.includes('insertTemplateVariable'), 'Template editor must not keep the removed variable-insertion control path.');
assert(source.includes('id="template-example"'), 'Template editor must keep a compact output summary.');
assert(source.includes('id="template-preview-open"') && source.includes('template-editor__preview-summary'), 'Preview must live inside the output summary.');
assert(!source.includes('Muốn xem câu này chạy ra sao?'), 'Template editor must omit the redundant preview callout.');
assert(source.includes('place_values'), 'Template editor must document the generated place-value wording variable.');
assert(source.includes('normalizeFillAnswer'), 'Fill-in answers must normalize textbook number spacing before grading.');
assert(source.includes('template-fill-layout'), 'Dynamic fill-in templates must use a multi-row layout.');
assert(source.includes('comparison-expression'), 'Comparison templates must render operands in separate, readable positions.');
assert(source.includes('formatQuestionDetailHTML'), 'Result details must render stored line breaks without showing raw <br> markup.');
assert(source.includes('matching-columns'), 'Matching questions must use a dedicated balanced column layout.');
assert(css.includes('white-space: nowrap'), 'Long mathematical expressions and matching labels must stay on one line.');
assert(source.includes("'\\u00a0'"), 'Math number formatting must use non-breaking spaces between thousands groups.');
assert(source.includes('template-editor__checks--places'), 'Place values must use a dedicated grouped grid layout.');
assert(source.includes('allowedPlaces'), 'Template editor must support multiple place-value selections.');
assert(source.includes('allowedDigits'), 'Template editor must support multiple digit selections.');
assert(source.includes('number.smallest_of_four'), 'The Template Bank must expose the smallest-of-four generator.');
assert(source.includes('number.largest_of_four'), 'The Template Bank must expose the largest-of-four generator.');
assert(source.includes('number.compose_from_places'), 'The Template Bank must expose the compose-number fill-in template.');
assert(source.includes('number.missing_expanded_addend'), 'The Template Bank must expose the expanded-form fill-in template.');
assert(source.includes('number.four_operations_fill_blanks'), 'The Template Bank must expose the Topic 1 four-operations fill-in template.');
assert(source.includes('number.four_operations_expressions'), 'The Template Bank must expose the Topic 1 calculate-expression template.');
assert(source.includes('number.four_arithmetic_blanks'), 'The Template Bank must expose the four-arithmetic fill-in template.');
assert(source.includes('number.four_arithmetic_comparisons'), 'The Template Bank must expose the four-arithmetic drag-comparison template.');
assert(source.includes('number.neighbor_numbers'), 'The Template Bank must expose the adjacent-number fill-in template.');
assert(source.includes('number.natural_sequence'), 'The Template Bank must expose the reusable natural-sequence generator.');
assert(indexHtml.includes('src/question-templates/grade-4/math/natural-sequence.js'), 'The browser must load the natural-sequence generator before the Template Bank registry.');
assert(source.includes('template-natural-sequence-steps'), 'Natural-sequence templates must expose configurable steps.');
assert(source.includes('template-natural-sequence-length-min'), 'Natural-sequence templates must expose configurable sequence lengths.');
assert(source.includes('template-natural-sequence-blank-min'), 'Natural-sequence templates must expose configurable blank counts.');
assert(source.includes('number.compare_number_forms'), 'The Template Bank must expose the comparison template.');
assert(source.includes('number.match_number_words'), 'The Template Bank must expose the number-word matching generator.');
assert(source.includes('number.place_value_true_false'), 'The Template Bank must expose the place-value true/false generator.');
assert(source.includes('number.safe_password_by_place_value'), 'The Template Bank must expose the safe-password generator.');
assert(source.includes('g4-m-angle-count-in-polygon'), 'The Template Bank must expose the angle-count-in-polygon generator.');
assert(source.includes('g4-m-angle-drag-classify'), 'The Template Bank must expose the angle-drag-classify generator.');
assert(source.includes('g4-m-angle-clock-classify'), 'The Template Bank must expose the angle-clock-classify generator.');
assert(source.includes('g4-m-angle-count-eight-angles'), 'The Template Bank must expose the eight-angle-count generator.');
[
  'g4-m-add-sub-multi-digit',
  'g4-m-add-sub-word-problem',
  'g4-m-add-sub-missing-term',
  'g4-m-add-sub-missing-digit',
  'g4-m-addition-property-fill',
  'g4-m-add-sub-expression',
  'g4-m-sum-difference-direct',
  'g4-m-sum-difference-context',
  'g4-m-add-sub-true-false'
].forEach(generatorKey => {
  assert(source.includes(generatorKey), `The Template Bank must expose the Grade 4 Topic 5 generator ${generatorKey}.`);
});
assert(source.includes('item.name || item.generator_key'), 'The Template Bank table must show the saved template name before its code key.');
assert(source.includes('renderTemplatePreview(generator)'), 'Templates must use a focused generated preview instead of an unrelated legacy image.');
assert(migration.includes("'2. Góc và đơn vị đo góc'"), 'The Template Bank must keep the four angle templates in Grade 4 Math Topic 2.');
assert(css.includes('question-box--safe-password'), 'Safe-password questions must have a dedicated image layout.');
assert(source.includes('safe-password-open-v1.png'), 'A correct safe-password answer must reveal the opened safe image.');
assert(source.includes('template-safe-password-min-length'), 'Safe-password templates must let administrators choose the minimum number of password cells.');
assert(source.includes('template-safe-password-max-length'), 'Safe-password templates must let administrators choose the maximum number of password cells.');
assert(source.includes('template-safe-password-condition1-places'), 'Safe-password templates must expose configurable places for condition 1.');
assert(source.includes('template-safe-password-condition2-places'), 'Safe-password templates must expose configurable places for condition 2.');
assert(source.includes('template-safe-password-condition1-digits'), 'Safe-password templates must expose configurable digits for condition 1.');
assert(source.includes('template-safe-password-condition2-digits'), 'Safe-password templates must expose configurable digits for condition 2.');
assert(source.includes('template-safe-password-condition1-scope'), 'Safe-password templates must let administrators distinguish a class condition from a place condition.');
assert(source.includes("rule.hidden = false"), 'Safe-password configuration controls must remain visible after the template editor renders.');
assert(source.includes('Lớp triệu (trăm triệu, chục triệu, triệu)'), 'The editor must define a class as its three constituent places.');
assert(source.includes('Lớp tỷ (trăm tỷ, chục tỷ, tỷ)'), 'The editor must offer the four requested number classes through lớp tỷ.');
assert(source.includes("condition1Scope = generatorKey === 'number.safe_password_by_place_value' ? 'random'"), 'Safe-password condition 1 must randomly choose from configured classes and places.');
assert(!source.includes('renderSafePasswordCells'), 'Safe-password questions must not overlay SVG password cells on the safe image.');
assert(migration.includes("'number.safe_password_by_place_value'"), 'Migration must seed the safe-password template.');
assert(migration.includes("'g4-m-angle-count-in-polygon'"), 'Migration must seed the polygon angle-count template.');
assert(migration.includes("'g4-m-angle-drag-classify'"), 'Migration must seed the drag-classify angle template.');
assert(migration.includes("'g4-m-angle-clock-classify'"), 'Migration must seed the clock angle template.');
assert(migration.includes("'g4-m-angle-count-eight-angles'"), 'Migration must seed the eight-angle-count template.');
assert(source.includes('tf-statement'), 'Gameplay must render a separate true/false choice for each statement.');
assert(source.includes('Đối chiếu trùng khớp'), 'The Template Bank must select the matching question type.');
assert(source.includes("'Đúng/Sai'"), 'The Template Bank question-type list must include true/false questions.');
assert(source.includes("'Chuỗi Quy luật'"), 'The Template Bank question-type list must include pattern questions.');
assert(source.includes("'Kéo thả'"), 'The Template Bank question-type list must include drag-and-drop questions.');
assert(source.includes('template-match-shapes'), 'The matching template must expose configurable shapes.');
assert(source.includes('template-match-digits'), 'The matching template must expose configurable number lengths.');
assert(source.includes('template-arithmetic-min-digits'), 'Four-arithmetic templates must expose the minimum number length.');
assert(source.includes('template-arithmetic-max-digits'), 'Four-arithmetic templates must expose the maximum number length.');
assert(source.includes('template-arithmetic-operations'), 'Four-arithmetic templates must expose selectable operations.');
assert(source.includes("checkbox('*', 'Phép nhân (×)'"), 'Four-arithmetic templates must expose multiplication as an operation.');
assert(source.includes("checkbox('/', 'Phép chia (÷)'"), 'Four-arithmetic templates must expose division as an operation.');
assert(source.includes('template-arithmetic-layouts'), 'Four-arithmetic templates must expose selectable two-side layouts.');
assert(source.includes('template-arithmetic-blank-positions'), 'The fill-in template must expose selectable blank positions.');
assert(source.includes("checkbox('fourth', 'Số thứ tư'"), 'The fill-in template must let administrators select the fourth operand as a blank.');
assert(!source.includes('template-arithmetic-comparisons'), 'The drag-comparison template must always include all three signs instead of exposing a limited sign configuration.');
assert(css.includes('comparison-drag-slot'), 'Four-arithmetic comparisons must use a dedicated circular drop slot.');
assert(source.includes('Tỷ lệ sinh số'), 'The matching template must label digit weights clearly.');
assert(css.includes('template-editor__rule--matching-controls'), 'Matching configuration must span the rule grid without overlapping fields.');
assert(source.includes('generateTemplateQuestion'), 'Gameplay must generate questions from active template configurations.');
assert(migration.includes("'number.smallest_of_four'"), 'Migration must seed the smallest-of-four template.');
assert(migration.includes("'number.largest_of_four'"), 'Migration must seed the largest-of-four template.');
assert(migration.includes("'number.compose_from_places'"), 'Migration must seed the compose-number template.');
assert(migration.includes("'number.missing_expanded_addend'"), 'Migration must seed the expanded-form template.');
assert(migration.includes("'number.four_arithmetic_blanks'"), 'Migration must seed the four-arithmetic fill-in template.');
assert(migration.includes("'number.four_arithmetic_comparisons'"), 'Migration must seed the four-arithmetic drag-comparison template.');
assert(migration.includes('Grade 4 Math, Topic 1: COPY the ten reusable templates'), 'Migration must copy the reusable Grade 4 Math templates for Topic 1.');
assert(migration.includes('The originals stay in their current topic'), 'Migration must preserve the original Topic 3 templates.');
assert(migration.includes("'1. Ôn tập và bổ sung'"), 'Migration must create configured copies for the real Grade 4 Topic 1.');
assert(migration.includes("'number.four_operations_fill_blanks'"), 'Migration must add the Topic 1 four-operations fill-in template.');
assert(migration.includes("'number.four_operations_expressions'"), 'Migration must add the Topic 1 calculate-expression template.');
assert(migration.includes("'number.neighbor_numbers'"), 'Migration must seed the adjacent-number template.');
assert(migration.includes("'number.natural_sequence'"), 'Migration must seed the natural-sequence template.');
assert(migration.includes("'number.compare_number_forms'"), 'Migration must seed the comparison template.');
assert(migration.includes("'number.match_number_words'"), 'Migration must seed the number-word matching template.');
assert(migration.includes("'number.place_value_true_false'"), 'Migration must seed the place-value true/false template.');
assert(migration.includes("'Đúng/Sai về lớp của chữ số', 'Lớp 4', 'Toán', 'Học kỳ 1', '3. Số có nhiều chữ số'"), 'The true/false template must be seeded under the Grade 4 multi-digit-number topic.');
assert(migration.includes('CREATE TABLE IF NOT EXISTS public.question_templates'), 'Migration must create template storage.');
assert(migration.includes('templates_write_teacher'), 'Only teachers may modify templates in Supabase.');

console.log('Template Bank contract verified.');
