const assert = require('assert');
const fs = require('fs');

const source = fs.readFileSync('src/main.js', 'utf8');
const css = fs.readFileSync('src/style.css', 'utf8');
const migration = fs.readFileSync('supabase_question_templates.sql', 'utf8');

assert(source.includes("{ id: 'templates', label: 'Kho Template' }"), 'Admin must show a Template Bank tab before Question Bank.');
assert(source.includes('renderTemplates(box)'), 'Admin must render the Template Bank.');
assert(source.includes("setTemplateFilter('classlevel'"), 'Template Bank must offer grade filtering.');
assert(source.includes('template-prompt'), 'Template editor must offer an editable prompt.');
assert(source.includes('template-editor'), 'Template editor must use the full modal width through its dedicated layout.');
assert(!source.includes('onclick="app.admin.renderTemplateForm()"'), 'Template Bank must not offer a blank template creation flow.');
assert(source.includes('Lưu thành bản mới'), 'Template editor must allow copying an existing configuration.');
assert(source.includes('template-select-all'), 'Template editor must provide quick select-all controls.');
assert(source.includes('hundredBillions'), 'Template editor must support place values through hundreds of billions.');
assert(source.includes('formatMathText'), 'Math content must format long numbers with textbook-style spaces.');
assert(source.includes('formatTemplateNumberInput'), 'Template range inputs must format numbers while editing.');
assert(source.includes('template-variable'), 'Template editor must show insertable variables for administrators.');
assert(source.includes('presetPrompt'), 'Templates stored with {question} must show a readable default prompt in the editor.');
assert(source.includes('defaultPrompt'), 'Every dynamic template must declare its readable default prompt.');
assert(source.includes('insertTemplateVariable'), 'Template editor must let administrators insert a variable into the prompt.');
assert(source.includes('place_values'), 'Template editor must document the generated place-value wording variable.');
assert(source.includes('normalizeFillAnswer'), 'Fill-in answers must normalize textbook number spacing before grading.');
assert(source.includes('template-fill-layout'), 'Dynamic fill-in templates must use a multi-row layout.');
assert(source.includes('comparison-expression'), 'Comparison templates must render operands in separate, readable positions.');
assert(source.includes('formatQuestionDetailHTML'), 'Result details must render stored line breaks without showing raw <br> markup.');
assert(source.includes('matching-columns'), 'Matching questions must use a dedicated balanced column layout.');
assert(css.includes('white-space: nowrap'), 'Long mathematical expressions and matching labels must stay on one line.');
assert(source.includes("'\\u00a0'"), 'Math number formatting must use non-breaking spaces between thousands groups.');
assert(source.includes('template-editor__checks--places'), 'Place values must use a dedicated grouped grid layout.');
assert(source.includes('allowedPlaces'), 'Template editor must support multiple place-value selections.');
assert(source.includes('allowedDigits'), 'Template editor must support multiple digit selections.');
assert(source.includes('number.smallest_of_four'), 'The Template Bank must expose the smallest-of-four generator.');
assert(source.includes('number.largest_of_four'), 'The Template Bank must expose the largest-of-four generator.');
assert(source.includes('number.compose_from_places'), 'The Template Bank must expose the compose-number fill-in template.');
assert(source.includes('number.missing_expanded_addend'), 'The Template Bank must expose the expanded-form fill-in template.');
assert(source.includes('number.neighbor_numbers'), 'The Template Bank must expose the adjacent-number fill-in template.');
assert(source.includes('number.compare_number_forms'), 'The Template Bank must expose the comparison template.');
assert(source.includes('number.match_number_words'), 'The Template Bank must expose the number-word matching generator.');
assert(source.includes('number.place_value_true_false'), 'The Template Bank must expose the place-value true/false generator.');
assert(source.includes('number.safe_password_by_place_value'), 'The Template Bank must expose the safe-password generator.');
assert(css.includes('question-box--safe-password'), 'Safe-password questions must have a dedicated image layout.');
assert(source.includes('safe-password-open-v1.png'), 'A correct safe-password answer must reveal the opened safe image.');
assert(source.includes('template-safe-password-min-length'), 'Safe-password templates must let administrators choose the minimum number of password cells.');
assert(source.includes('template-safe-password-max-length'), 'Safe-password templates must let administrators choose the maximum number of password cells.');
assert(source.includes('template-safe-password-condition1-places'), 'Safe-password templates must expose configurable places for condition 1.');
assert(source.includes('template-safe-password-condition2-places'), 'Safe-password templates must expose configurable places for condition 2.');
assert(source.includes('template-safe-password-condition1-digits'), 'Safe-password templates must expose configurable digits for condition 1.');
assert(source.includes('template-safe-password-condition2-digits'), 'Safe-password templates must expose configurable digits for condition 2.');
assert(source.includes('template-safe-password-condition1-scope'), 'Safe-password templates must let administrators distinguish a class condition from a place condition.');
assert(source.includes('Lớp triệu (trăm triệu, chục triệu, triệu)'), 'The editor must define a class as its three constituent places.');
assert(source.includes('Lớp tỷ (trăm tỷ, chục tỷ, tỷ)'), 'The editor must offer the four requested number classes through lớp tỷ.');
assert(source.includes("condition1Scope = generatorKey === 'number.safe_password_by_place_value' ? 'random'"), 'Safe-password condition 1 must randomly choose from configured classes and places.');
assert(!source.includes('renderSafePasswordCells'), 'Safe-password questions must not overlay SVG password cells on the safe image.');
assert(migration.includes("'number.safe_password_by_place_value'"), 'Migration must seed the safe-password template.');
assert(source.includes('tf-statement'), 'Gameplay must render a separate true/false choice for each statement.');
assert(source.includes('Đối chiếu trùng khớp'), 'The Template Bank must select the matching question type.');
assert(source.includes("'Đúng/Sai'"), 'The Template Bank question-type list must include true/false questions.');
assert(source.includes("'Chuỗi Quy luật'"), 'The Template Bank question-type list must include pattern questions.');
assert(source.includes("'Kéo thả'"), 'The Template Bank question-type list must include drag-and-drop questions.');
assert(source.includes('template-match-shapes'), 'The matching template must expose configurable shapes.');
assert(source.includes('template-match-digits'), 'The matching template must expose configurable number lengths.');
assert(source.includes('Tỷ lệ sinh số'), 'The matching template must label digit weights clearly.');
assert(css.includes('template-editor__rule--matching-controls'), 'Matching configuration must span the rule grid without overlapping fields.');
assert(source.includes('generateTemplateQuestion'), 'Gameplay must generate questions from active template configurations.');
assert(migration.includes("'number.smallest_of_four'"), 'Migration must seed the smallest-of-four template.');
assert(migration.includes("'number.largest_of_four'"), 'Migration must seed the largest-of-four template.');
assert(migration.includes("'number.compose_from_places'"), 'Migration must seed the compose-number template.');
assert(migration.includes("'number.missing_expanded_addend'"), 'Migration must seed the expanded-form template.');
assert(migration.includes("'number.neighbor_numbers'"), 'Migration must seed the adjacent-number template.');
assert(migration.includes("'number.compare_number_forms'"), 'Migration must seed the comparison template.');
assert(migration.includes("'number.match_number_words'"), 'Migration must seed the number-word matching template.');
assert(migration.includes("'number.place_value_true_false'"), 'Migration must seed the place-value true/false template.');
assert(migration.includes("'Đúng/Sai về lớp của chữ số', 'Lớp 4', 'Toán', 'Học kỳ 1', '3. Số có nhiều chữ số'"), 'The true/false template must be seeded under the Grade 4 multi-digit-number topic.');
assert(migration.includes('CREATE TABLE IF NOT EXISTS public.question_templates'), 'Migration must create template storage.');
assert(migration.includes('templates_write_teacher'), 'Only teachers may modify templates in Supabase.');

console.log('Template Bank contract verified.');
