const assert=require('node:assert/strict');
const P=require('./src/modules/authoring-plan.js');
assert.deepEqual(P.amount(10,4),{value:.25,label:'0,25 đ',warning:false});
assert.equal(P.amount(10,3).warning,true);
assert.match(P.amount(10,3).label,/0,333333/);
assert.equal(P.amount(16,1).label,'0,625 đ');
assert.equal(P.amount(16,1).warning,true);
assert.equal(P.amount(8,1).warning,false);
assert.throws(()=>P.normalize({count:0,rows:[]}));
const plan=P.normalize({count:3,rows:[{hasSub:true,parts:3},{hasSub:false},{hasSub:true,parts:2}]});
assert.equal(plan.rows[1].parts,1);
const source=Array.from({length:6},(_,i)=>({type:'Điền khuyết',q:`${i} + ___ = 10`,ans:String(10-i)}));
const questions=P.assemble(plan,source);
assert.equal(questions.length,3);
assert.equal(questions[0].authoringParts.length,3);
assert.equal(questions[1].authoringParts,undefined);
assert.equal(P.validateRecord({questions}), '');
assert.equal(P.validateRecord({questions:questions.slice(1)}).length>0,true);
assert.throws(()=>P.assemble(plan,source.slice(0,5)));
console.log('Authoring score plan contracts passed');
