const assert = require('node:assert/strict');
const fs = require('node:fs');

const source = fs.readFileSync('src/main.js', 'utf8');
const ui = fs.readFileSync('src/modules/ui.js', 'utf8');
const migration = fs.readFileSync('supabase_auth_security.sql', 'utf8');
const adminFunction = fs.readFileSync('supabase/functions/admin-users/index.ts', 'utf8');
const css = fs.readFileSync('src/style.css', 'utf8') + fs.readFileSync('src/login-layout.css', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');
const classMigration = fs.readFileSync('supabase/migrations/20260906_game_users_class_name.sql', 'utf8');
const genderMigration = fs.readFileSync('supabase/migrations/20260907_game_users_gender.sql', 'utf8');

assert.match(source, /auth\.signInWithPassword/, 'Login must use Supabase Auth.');
assert.match(source, /auth_user_id/, 'Profiles must be linked to an Auth identity.');
assert.doesNotMatch(source, /u === 'admin' && p === '123'/, 'The default admin backdoor must be removed.');
assert.match(migration, /REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon/, 'Anonymous database access must be revoked.');
assert.match(migration, /private\.is_admin\(\)/, 'RLS must use a server-side admin check.');
assert.match(migration, /profiles_select_own_or_teacher/, 'Student profiles must be isolated by Auth identity.');
assert.match(adminFunction, /SUPABASE_SERVICE_ROLE_KEY/, 'Administrative account provisioning must keep the service key on the server.');
assert.doesNotMatch(adminFunction, /Access-Control-Allow-Origin': '\*'/, 'Admin function must not use a wildcard CORS origin.');
assert.match(adminFunction, /legacy_profile_linked/, 'Resetting a legacy student must link that profile to a new Auth account.');
assert.match(source, /student_not_found/, 'The teacher UI must explain why a password reset cannot be completed.');
assert.match(source, /auth_account_exists/, 'The teacher UI must explain when an Auth account already exists.');
assert.match(source, /!app\.data\.users\.find\(x => x\.id === data\.profile\.id\)/, 'Creating a student must not duplicate the realtime profile in the teacher list.');
assert.match(ui, /setButtonLoading\(buttonId, isLoading, loadingLabel/, 'Slow actions must show a clear loading state and prevent repeated clicks.');
assert.match(source, /setButtonLoading\('login-btn', true, 'Đang đăng nhập…'\)/, 'Login must visibly say that sign-in is in progress before fetching protected data.');
assert.match(html, /id="username"[^>]*placeholder="Tên đăng nhập: không dấu, viết liền, không khoảng trắng"/, 'The login field must explain that pupils enter only the short username.');
assert.match(html, /id="reg-class-name"/, 'Registration must offer the optional class subfield.');
assert.match(source, /class_name/, 'Client profile flows must preserve the class subfield.');
assert.match(adminFunction, /class_name/, 'Admin account provisioning must accept the class subfield.');
assert.match(adminFunction, /validClassName/, 'Admin account provisioning must bound the class subfield input.');
assert.match(classMigration, /ADD COLUMN IF NOT EXISTS class_name\s+text/i, 'The class subfield migration must be additive and repeatable.');
assert.match(html, /id="link-to-change-password"/, 'The login screen must offer a self-service password-change entry point.');
assert.match(html, /id="change-password-form"/, 'The password-change dialog must collect the required credentials.');
assert.match(html, /id="change-password-old"/, 'The dialog must require the current password.');
assert.match(html, /id="change-password-new"/, 'The dialog must collect the new password.');
assert.match(html, /id="change-password-confirm"/, 'The dialog must require confirmation of the new password.');
assert.match(source, /async changePassword\(\)/, 'The client must have a dedicated password-change flow.');
assert.match(source, /auth\.signInWithPassword\(\{ email, password: oldPassword \}\)/, 'The old password must be verified by Supabase Auth before it can be changed.');
assert.match(source, /auth\.updateUser\(\{ password: newPassword \}\)/, 'The new password must be updated through Supabase Auth, not a browser table update.');
assert.match(source, /changePasswordPending/, 'Password changes must prevent duplicate submissions while the request is pending.');
assert.match(source, /setButtonLoading\('change-password-submit', true, 'Đang cập nhật…'\)/, 'Password changes must show a clear loading state.');
assert.match(source, /Promise\.all\(\[/, 'Independent post-login data loads must run in parallel.');
assert.match(source, /avatar_key/, 'New student profiles must save their selected avatar.');
assert.match(migration, /avatar_key TEXT/, 'The user profile migration must persist an avatar key.');

assert.match(html, /name="reg-avatar"/, 'Registration must offer an avatar selection.');
assert.match(html, /id="player-info" class="player-info-card"/, 'The map must retain a dedicated player information card.');
assert.match(source, /player-info-card__avatar/, 'The player card must render the chosen avatar.');
assert.match(source, /Đang đăng nhập…/, 'The loading state must use the clear Vietnamese sign-in label.');
assert.match(ui, /button-loading/, 'Image buttons must render a visible loading treatment instead of transparent text.');
assert.match(html, /value="boy-short"/, 'Registration must include boy avatars.');
assert.match(html, /value="girl-long"/, 'Registration must include girl avatars.');
assert.match(html, /value="girl-doll"/, 'Registration must include varied girl hairstyles.');
assert.match(html, /value="boy-reader"/, 'Registration must include the second set of boy avatars.');
assert.match(html, /value="girl-inventor"/, 'Registration must include the second set of girl avatars.');
assert.match(html, /setAvatarGroup\('cartoons'/, 'Registration must offer a dedicated Cartoon avatar tab.');
assert.match(html, /value="cartoon-robot-cat"/, 'Registration must include original cartoon avatars.');
assert.match(source, /cartoon-robot-cat/, 'Cartoon avatars must be valid profile avatar keys.');
assert.match(css, /avatars-cartoons-sprite-v1\.webp/, 'Cartoon avatars must use their own sprite sheet.');
assert.match(source, /setAvatarGroup\(group, button\)/, 'The avatar picker must let pupils switch between boy and girl avatar groups.');
assert.match(css, /overflow-x: auto/, 'Avatar choices must use a horizontal scroller instead of adding a second row.');
assert.match(css, /input:checked \+ span \{[^}]*background-color/, 'Selecting an avatar must not overwrite its sprite background image.');
assert.match(css, /label:hover span/, 'Hovering an avatar must enlarge its portrait for easier selection.');
assert.match(css, /min-inline-size: 0/, 'The avatar fieldset must be allowed to shrink inside the registration panel.');
assert.match(css, /max-width: 100%/, 'The avatar picker must never exceed its registration panel.');
assert.doesNotMatch(html, /<em>/, 'Avatar names must not be shown beneath the portraits.');
assert.match(html, /register-panel--wide/, 'Registration must identify the new landscape panel.');
assert.match(html, /register_frame_wide\.png/, 'Registration must use the approved wide frame asset.');
assert.match(html, /register-form-grid/, 'Registration fields must be arranged in a two-column grid.');
assert.match(html, /id="reg-gender"/, 'Registration must allow pupils to optionally declare gender.');
assert.match(css, /#register-screen \.register-panel\s*\{[\s\S]*?aspect-ratio:\s*3\s*\/\s*2\.45/, 'The registration panel must keep the approved 3:2.45 landscape ratio.');
assert.match(genderMigration, /gender\s+IS\s+NULL\s+OR\s+gender\s+IN\s*\(\s*'male'\s*,\s*'female'\s*\)/i, 'The gender constraint must allow only male/female or null.');
assert.doesNotMatch(genderMigration, /['"]other['"]|Khác \/ không muốn nêu/i, 'The gender migration must not retain the removed other value.');
assert.doesNotMatch(adminFunction, /['"]other['"]|Khác \/ không muốn nêu/i, 'The admin account function must reject the removed other value.');
assert.doesNotMatch(html, /value="other"|Khác \/ không muốn nêu/i, 'Registration must not offer the removed other value.');
assert.doesNotMatch(source, /other:\s*['"]Khác \/ không muốn nêu|option\.value === 'other'/i, 'The client gender labels and filters must not render the removed other value.');

console.log('Supabase Auth and RLS security contract verified.');
