const {test,expect}=require('@playwright/test');
async function open(page){await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'application/javascript',body:''}));await page.route('**/*.supabase.co/**',r=>r.abort());await page.goto('/');await page.evaluate(()=>window.gameTemplatesReady);}
async function play(page,columns=6){return page.evaluate(columns=>{const q=CompleteTableTemplates.generateQuestion('number.complete_place_table',{placeColumns:columns});app.data.currentUser={username:'table-local',role:'student',classlevel:'4'};app.game.state={subject:'math',questions:[q],currentIdx:0,score:0,historyDetails:[]};document.querySelectorAll('.screen,.game-view').forEach(e=>e.classList.remove('active'));document.getElementById('game-screen').classList.add('active');document.getElementById('game-play-view').classList.add('active');app.game.loadQuestion();return q;},columns);}
for(const width of [1280,1440,1024])test(`table inputs and four rows fit ${width}`,async({page})=>{
 await page.setViewportSize({width,height:width===1280?720:width===1440?900:768});await open(page);const q=await play(page);
 const table=page.locator('#game-options-container .complete-table');await expect(table.locator('thead tr')).toHaveCount(1);await expect(table.locator('tbody tr')).toHaveCount(4);await expect(table.locator('th')).toHaveCount(8);
 for(const input of await table.locator('input,textarea').all())await expect(input).toBeInViewport();
 expect(await table.evaluate(t=>t.scrollWidth<=t.clientWidth+1)).toBe(true);
 expect(await table.evaluate(t=>Array.from(t.parentElement.childNodes).filter(n=>n.nodeType===3).map(n=>n.textContent.trim()).join(''))).toBe('');
 await page.evaluate(q=>{const container=document.getElementById('game-options-container');CompleteTableTemplates.restore(container,'practice',q.ans);container.dispatchEvent(new Event('input'));},q);
 await expect(page.locator('#submit-ans-btn')).toBeEnabled();if(width===1280)await page.screenshot({path:'.tmp/complete-table-1280.png'});
 await page.evaluate(()=>app.game.submitAnswer());expect(await page.evaluate(()=>app.game.state.score)).toBe(1);await expect(table.locator('.complete-table__correct')).toHaveCount(4);
});
test('exam restores all fields, gives quarter points and prints only missing cells',async({page})=>{await open(page);const result=await page.evaluate(()=>{
 const q=CompleteTableTemplates.generateQuestion('number.complete_place_table',{placeColumns:7});document.getElementById('exam-questions-container').innerHTML=app.exam.renderQuestionInput(q,0);app.exam.state.questions=[q];app.exam.applySavedAnswers([q.ans]);const answer=app.exam.readQuestionAnswer(q,0);const answers=JSON.parse(answer);answers[0]={};const detail=app.game.createHistoryDetail(q,answer,true);
 return {valid:app.data.validateQuestionScoring(q),score:app.game.calculateQuestionScore(q,answer),partial:app.game.calculateQuestionScore(q,answers),print:app.admin.renderExamPrintQuestion(q,0),history:app.game.formatHistoryQuestion(detail)};
 });expect(result.valid).toBe('');expect(result.score.points).toBe(1);expect(result.partial.points).toBe(.75);expect(result.print).toContain('Hàng triệu');expect(result.print).toContain('complete-table__blank');expect(result.print).not.toContain('<input');expect(result.history).toContain('complete-table');});
test('admin edits column count and previews four rows',async({page})=>{await open(page);await page.evaluate(()=>{app.data.currentUser={username:'teacher',role:'admin',classlevel:'4'};app.admin.openCompleteTableTemplate();document.getElementById('treasure-modal').style.display='block';});await expect(page.locator('#template-generator')).toHaveValue('number.complete_place_table');await expect(page.locator('#template-table-columns')).toHaveValue('6');await page.locator('#template-table-columns').fill('4');const result=await page.evaluate(()=>{const t=app.admin.collectTemplateForm();const q=app.data.generateTemplateQuestion(t);return {columns:q.placeColumns,rows:q.tableRows.length,preview:app.admin.renderGeneratedTemplatePreview(q)};});expect(result.columns).toBe(4);expect(result.rows).toBe(4);expect(result.preview).toContain('Hàng nghìn');expect(result.preview).not.toContain('Hàng chục nghìn');});

test('row progress, draft restore and next fill question keep independent answers',async({page})=>{
 await open(page);const q=await play(page);const result=await page.evaluate(q=>{
 const c=document.getElementById('game-options-container');const first=c.querySelector('input,textarea');first.value='1';first.dispatchEvent(new Event('input',{bubbles:true}));const partial=app.game.getCompletedQuestionPartCount();
 CompleteTableTemplates.restore(c,'practice',q.ans);c.dispatchEvent(new Event('input'));const full=app.game.getCompletedQuestionPartCount();const count=app.game.getQuestionPartCount();
 app.game.saveAttemptDraft('practice');app.game.state.selectedAns=null;const resumed=app.game.resumeSavedAttempt();const restored=app.game.calculateQuestionScore(q,app.game.state.selectedAns).points;
 app.game.state.questions=[{type:'Điền khuyết',q:'2 + 3 = ___',ans:'5'}];app.game.state.currentIdx=0;app.game.loadQuestion();const input=document.querySelector('#game-options-container input, #game-question-container input');input.value='5';input.dispatchEvent(new Event('input',{bubbles:true}));return {partial,full,count,resumed,restored,answer:app.game.state.selectedAns};
 },q);expect(result).toEqual({partial:0,full:4,count:4,resumed:true,restored:1,answer:'5'});
});
test('separate print window includes complete table layout CSS',async({page})=>{await open(page);const output=await page.evaluate(()=>{
 const q=CompleteTableTemplates.generateQuestion('number.complete_place_table');app.data.exams=[{name:'Bảng',questions:[q]}];let html='';const fake={closed:false,setTimeout(){},document:{open(){},write(value){html=value},close(){},fonts:{ready:Promise.resolve()},querySelector(){return null}},focus(){},print(){}};const original=window.open;window.open=()=>fake;app.admin.printExam(0);window.open=original;return html;
 });expect(output).toContain('.complete-table__read-col');expect(output).toContain('complete-table__blank');});

test('short numbers leave higher places blank while internal zeros remain required',async({page})=>{await open(page);const result=await page.evaluate(()=>{
 const q=CompleteTableTemplates.generateQuestion('number.complete_place_table',{},()=>0);const c=document.getElementById('game-options-container');c.innerHTML=CompleteTableTemplates.markup(q,'short');CompleteTableTemplates.restore(c,'short',q.ans);const a=CompleteTableTemplates.read(c,'short');const before=CompleteTableTemplates.score(q,a).points;const missing=c.querySelectorAll('[data-table-place="0"]').length;const zero=c.querySelector('[data-table-row="0"][data-table-place="2"]');zero.value='';return {before,missing,after:CompleteTableTemplates.score(q,CompleteTableTemplates.read(c,'short')).points,complete:CompleteTableTemplates.completed(q,a)};
 });expect(result).toEqual({before:1,missing:0,after:.75,complete:4});});
