const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
async function setup(page){await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'application/javascript',body:''}));await page.route('**/*.supabase.co/**',r=>r.abort());await page.goto('/');await page.evaluate(()=>{app.data.currentUser={role:'admin',username:'teacher'};app.admin.openComposer('worksheets');app.worksheetStudio.openImport();const feedback=app.worksheetStudio.feedback.bind(app.worksheetStudio);app.worksheetStudio.feedback=(...args)=>{feedback(...args);};});}
test('OpenCV worker giữ chữ đen, lọc mực màu và PaddleOCR đọc tiếng Việt',async({page},info)=>{test.setTimeout(180000);await setup(page);const requests=[];page.on('request',r=>{if(r.url().includes('/paddle/')){requests.push({url:r.url(),method:r.method()});}});
const result=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=500;const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,1200,500);ctx.fillStyle='black';ctx.font='42px Arial';ctx.fillText('PHIẾU HỌC TẬP',60,80);ctx.fillText('1. Điền chữ số: 6000 × 5 = .................',60,180);ctx.fillStyle='#aa0088';ctx.fillText('30000',450,250);const result=await app.worksheetLocalImport.runPaddle(canvas,true);ctx.fillStyle='black';ctx.fillRect(70,310,100,30);const doc=await app.worksheetLocalImport.readCanvas(canvas,'bai.png',1,[{x:.05,y:.6,width:.2,height:.1}],true);const source=app.worksheetLocalImport.sourcePages.at(-1);app.worksheetSourceTools.show(source);document.getElementById('ws-reset-region').click();const restored=app.worksheetSourceTools.canvas.getContext('2d').getImageData(75,315,1,1).data[0]===0;return {words:result.words,notes:result.notes,doc,restored};});fs.writeFileSync(info.outputPath('result.json'),JSON.stringify(result,null,2));expect(result.words.map(w=>w.text).join('\n')).toContain('6000');expect(result.words.map(w=>w.text).join('\n')).not.toContain('30000');expect(requests.every(r=>new URL(r.url).hostname==='127.0.0.1'&&r.method==='GET')).toBe(true);expect(requests.some(r=>r.url.endsWith('.tar'))).toBe(true);expect(result.doc.pages[0].blocks[0].text).toContain('Điền chữ số');expect(result.restored).toBe(true);
});
test('hai ảnh mẫu: 2 trang nguồn, 3 nhóm, bảng 8 cột và 6 bài',async({page},info)=>{test.skip(!process.env.WORKSHEET_QA_IMAGE||!process.env.WORKSHEET_QA_IMAGE_2,'Ảnh riêng chỉ dùng cho QA cục bộ');test.setTimeout(300000);await setup(page);const doc=await page.evaluate(async(names)=>{const all=[];for(const name of names){const bytes=await fetch(name.url).then(r=>r.arrayBuffer());const file=new File([bytes],name.name,{type:'image/jpeg'});all.push(await app.worksheetLocalImport.extract(file));}return {docs:all,sources:app.worksheetLocalImport.sourcePages.length,diagnostics:app.worksheetLocalImport.sourcePages.map(s=>({grid:s.grid,notes:s.notes,words:s.words,original:s.original.toDataURL(),prepared:s.prepared.toDataURL()}))};},[{url:'/__qa1',name:'trang1.jpg'},{url:'/__qa2',name:'trang2.jpg'}]);for(const [i,d] of doc.diagnostics.entries()){for(const kind of ['original','prepared']){fs.writeFileSync(info.outputPath(`${i}-${kind}.png`),Buffer.from(d[kind].split(',')[1],'base64'));delete d[kind];}}fs.writeFileSync(info.outputPath('photos.json'),JSON.stringify(doc,null,2));expect(doc.sources).toBe(2);expect(doc.docs.flatMap(d=>d.pages)).toHaveLength(3);expect(doc.docs.flatMap(d=>d.pages.flatMap(p=>p.blocks))).toHaveLength(6);const table=doc.docs[0].pages[0].blocks.find(b=>b.kind==='table');expect(table.columns).toHaveLength(8);expect(table.rows).toHaveLength(8);expect(table.rows[0][0]).toMatch(/30\s*078/);expect(table.rows[0].slice(1).every(cell=>cell==='___')).toBe(true);expect(doc.docs[1].pages[1].startNewPage).toBe(false);expect(doc.docs[1].pages[0].blocks[0].lines).toBeGreaterThanOrEqual(5);expect(doc.docs[1].pages[0].blocks[1].lines).toBeGreaterThanOrEqual(5);
});
test.beforeEach(async({page})=>{for(const [path,key] of [['/__qa1','WORKSHEET_QA_IMAGE'],['/__qa2','WORKSHEET_QA_IMAGE_2']])if(process.env[key])await page.route('**'+path,r=>r.fulfill({contentType:'image/jpeg',body:fs.readFileSync(process.env[key])}));});
