-- Kho Phiếu học tập độc lập với game_exams; không sao chép hoặc xóa dữ liệu đề.
BEGIN;

CREATE TABLE IF NOT EXISTS public.game_worksheets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    classlevel text NOT NULL,
    subject text NOT NULL,
    period text NOT NULL DEFAULT 'Học Kỳ 1',
    questions jsonb NOT NULL DEFAULT '[]'::jsonb
);

ALTER TABLE public.game_worksheets ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.game_worksheets ADD COLUMN IF NOT EXISTS classlevel text;
ALTER TABLE public.game_worksheets ADD COLUMN IF NOT EXISTS subject text;
ALTER TABLE public.game_worksheets ADD COLUMN IF NOT EXISTS period text DEFAULT 'Học Kỳ 1';
ALTER TABLE public.game_worksheets ADD COLUMN IF NOT EXISTS questions jsonb DEFAULT '[]'::jsonb;

ALTER TABLE public.game_worksheets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.game_worksheets FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.game_worksheets TO authenticated;

-- Thay riêng các policy của Phiếu, giữ nguyên quyền của các khu vực khác.
DO $$
DECLARE item record; sequence_name text;
BEGIN
    FOR item IN SELECT policyname FROM pg_policies
        WHERE schemaname = 'public' AND tablename = 'game_worksheets'
    LOOP
        EXECUTE format('DROP POLICY %I ON public.game_worksheets', item.policyname);
    END LOOP;
    sequence_name := pg_get_serial_sequence('public.game_worksheets', 'id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
END $$;

CREATE POLICY worksheets_teacher_only ON public.game_worksheets
    FOR ALL TO authenticated
    USING ((SELECT private.is_admin()))
    WITH CHECK ((SELECT private.is_admin()));

NOTIFY pgrst, 'reload schema';
COMMIT;

-- Kết quả xác minh sau khi chạy: đủ 6 cột, RLS bật, policy dành cho giáo viên.
SELECT column_name, data_type FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'game_worksheets'
ORDER BY ordinal_position;
SELECT relrowsecurity FROM pg_class WHERE oid = 'public.game_worksheets'::regclass;
SELECT policyname, cmd FROM pg_policies
WHERE schemaname = 'public' AND tablename = 'game_worksheets';
